options:
  client_login_timeout:
    default: 60
    type: int
    description: >
      If a client connects but does not manage to login in this
      amount of time, it will be disconnected. Mainly needed to
      avoid dead connections stalling SUSPEND and thus online
      restart. [seconds]
  default_pool_size:
    default: 20
    type: int
    description: >
      How many server connections to allow per user/database
      pair. Can be overridden in the per-database configuration.
  ignore_startup_parameters:
    default: "application_name"
    type: string
    description: >
      By default, PgBouncer allows only parameters it can keep
      track of in startup packets - client_encoding, datestyle,
      timezone and standard_conforming_strings.

      All other parameters will raise an error. To allow other
      parameters, they can be specified here, so that pgbouncer
      knows that they are handled by admin and it can ignore
      them.
  listen_port:
    default: 6432
    type: int
    description: >
      Which port to listen on. Applies to both TCP and Unix sockets.
  max_client_conn:
    default: 100
    type: int
    description: >
      Maximum number of client connections allowed. When
      increased then the file descriptor limits should also be
      increased. Note that actual number of file descriptors
      used is more than max_client_conn.
  pool_mode:
    default: transaction
    type: string
    description: >
      Specifies when a server connection can be reused by other
      clients.
  reserve_pool_size:
    default: 0
    type: int
    description: >
      How many additional connections to allow to a pool. 0
      disables.
  server_check_delay:
    default: 30
    type: int
    description: >
      How long to keep released connections available for
      immediate re-use, without running sanity-check queries on
      it. If 0 then the query is ran always.
  server_connect_timeout:
    default: 15
    type: int
    description: >
        If connection and login wont finish in this amount of
        time, the connection will be closed. [seconds]
  server_idle_timeout:
    default: 600
    type: int
    description: >
      If a server connection has been idle more than this many
      seconds it will be dropped. If 0 then timeout is
      disabled. [seconds]
  server_lifetime:
    default: 3600
    type: int
    description: >
      The pooler will try to close server connections that have
      been connected longer than this. Setting it to 0 means the
      connection is to be used only once, then closed. [seconds]
  server_login_retry:
    default: 15
    type: int
    description: >
      If login failed, because of failure from connect() or
      authentication that pooler waits this much before retrying
      to connect. [seconds]
  wait_warn:
    default: 5
    type: int
    description: >
      The parameters to pass to the nrpe plugin
      check_pgbouncer_pool_waittime for warning level.
  wait_crit:
    default: 20
    type: int
    description: >
      The parameters to pass to the nrpe plugin check_pgbouncer_pool_waittime
      for critical level.
  conn_warn:
    default: 75
    type: int
    description: >
      The parameters to pass to the nrpe plugin
      check_pgbouncer_connection_count for warn level.
  conn_crit:
    default: 90
    type: int
    description: >
      The parameters to pass to the nrpe plugin
      check_pgbouncer_connection_count for critical level.
