#!/usr/bin/python3

import json
import subprocess

import amulet

d = amulet.Deployment(sentries=False)  # No sentries due to Bug #133143.

d.add('postgresql')
d.add('pgbouncer')
d.add('psql', 'postgresql-psql')
d.configure('psql', dict(database='explicitdb'))
d.relate('postgresql:db-admin', 'pgbouncer:backend-db-admin')
d.relate('psql:db', 'pgbouncer:db-proxy')

try:
    d.setup(timeout=900)
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise


def run(unit, cmd):
    # Due to Bug #133143, we can't use sentries. But no need for
    # sentries any more now that we have 'juju run'.
    output = subprocess.check_output(['juju', 'run', '--unit', unit, cmd])
    return output.decode('UTF-8').strip()


relid = run('psql/0', 'relation-ids db')
relinfo = json.loads(run(
    'psql/0',
    'relation-get --format=json -r {} - pgbouncer/0'.format(relid)))

from pprint import pprint
pprint(relinfo)

if True:
    amulet.raise_status(amulet.PASS)
else:
    amulet.raise_status(amulet.FAIL)
