#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm db-relation-changed hook

set -eux # -x for verbose logging to juju debug-log
. scripts/common

pgbouncer_name=$(relation-get pgbouncer_dbname)
db_name=$(relation-get database)
db_host=$(relation-get host)
db_port=$(relation-get port)

if [[ -z $pgbouncer_name ]]; then
	pgbouncer_name=$db_name
fi
if [[ -z $db_port ]]; then
	db_port=5432
fi

juju-log "Creating/Updating DB relations"
echo "$pgbouncer_name = dbname=${db_name} host=${db_host} port=${db_port}" > /var/run/juju/db-${JUJU_RELATION_ID}

juju-log "Generating new pgbouncer configuration"
update_config

juju-log "Reloading pgbouncer"
/usr/sbin/service pgbouncer reload
