#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm common functions used by various hooks

set -eux # -x for verbose logging to juju debug-log

_update_configs()
{

}
