#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm common functions used by various hooks

update_config()
{
	local pgbouncer_config="/etc/pgbouncer/pgbouncer.ini"
	local template="templates/pgbouncer.ini.tmpl"
	local juju_config=$(/bin/mktemp --suffix=.juju)

	config-get --format=json -o $juju_config
	# Copy existing config file to preserve permissions.
	cp -a $pgbouncer_config ${pgbouncer_config}.new
	hooks/template-generate.py -j $juju_config $template > ${pgbouncer_config}.new
	mv ${pgbouncer_config}.new $pgbouncer_config
	rm -f $juju_config
}
