#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm config-changed hook

set -eux # -x for verbose logging to juju debug-log
. scripts/common

juju-log "Generating new pgbouncer configuration and init script"
update_config

juju-log "Reloading pgbouncer"
/usr/sbin/service pgbouncer reload
