#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm install hook

set -eux # -x for verbose logging to juju debug-log
. scripts/common

juju-log "Installing pgbouncer package via apt-get"
apt-get -y install -- pgbouncer python-cheetah

# Make sure pgbouncer is enabled and set max open files
max_open_files=$(config-get max_open_files)
cat  >/etc/default/pgbouncer << EOF
START=1
ulimit -n $max_open_files
EOF

update_config

# Reload if pgbouncer is already running
/usr/sbin/service pgbouncer status
if [ $? -ne 0 ]; then
	juju-log "Reloading pgbouncer"
	/usr/sbin/service pgbouncer reload
fi
