#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

set -eux # -x for verbose logging to juju debug-log
. scripts/common

unit_name=${JUJU_UNIT_NAME////-}
nagios_hostname="$(config-get nagios_context)-${unit_name}" 
nagios_logdir='/var/log/nagios'
nagios_check_script=/usr/local/lib/nagios/plugins/check-pgbouncer.py
nagios_servicegroup=$(config-get nagios_context)
address=$(config-get listen_addr)
if [ "$address" = "*" ]; then
    address=$(unit-get private-address)
fi
listen_port=$(config-get listen_port)
wait_warn=$(config-get wait_warn)
wait_crit=$(config-get wait_crit)

nagios_uid=$(getent passwd nagios | awk -F: '{ print $3}')
nagios_gid=$(getent passwd nagios | awk -F: '{ print $4}')
if [ $? -ne 0 ]; then
    juju-log "Nagios user not setup, exiting"
    exit 1
fi

if [ -d /usr/local/lib/nagios/plugins/ ]; then
    cp $CHARM_DIR/scripts/check-pgbouncer.py $nagios_check_script
    chmod 755 $nagios_check_script
fi

if [ ! -d $nagios_logdir ]; then
    mkdir $nagios_logdir
    chown nagios:nagios $nagios_logdir 
fi

# Remove existing checks to start clean
for FILE in /var/lib/nagios/export/*check_pgbouncer*.cfg; do
    rm -f $FILE
done

# NRPE check files
nrpe_check_pgbouncer_connection_count="/etc/nagios/nrpe.d/check_pgbouncer_connection_count.cfg"
nrpe_check_pgbouncer_pool_waittime="/etc/nagios/nrpe.d/check_pgbouncer_pool_waittime.cfg"
nrpe_check_pgbouncer_connection_count_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_connection_count.tmpl"
nrpe_check_pgbouncer_pool_waittime_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_pool_waittime.tmpl"
cheetah fill --env --stdout $nrpe_check_pgbouncer_connection_count_template > $nrpe_check_pgbouncer_connection_count
cheetah fill --env --stdout $nrpe_check_pgbouncer_pool_waittime_template > $nrpe_check_pgbouncer_pool_waittime

# Exported service files
nrpe_check_pgbouncer_connection_count_service_file="/var/lib/nagios/export/service__${nagios_servicegroup}-${nagios_hostname}_check_pgbouncer_connection_count.cfg"
nrpe_check_pgbouncer_pool_waittime_service_file="/var/lib/nagios/export/service__${nagios_servicegroup}-${nagios_hostname}_check_pgbouncer_pool_waittime.cfg"
nrpe_check_pgbouncer_connection_count_service_file_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_connection_count_service_file.tmpl"
nrpe_check_pgbouncer_pool_waittime_service_file_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_pool_waittime_service_file.tmpl"
cheetah fill --env --stdout $nrpe_check_pgbouncer_connection_count_service_file_template > $nrpe_check_pgbouncer_connection_count_service_file
cheetah fill --env --stdout $nrpe_check_pgbouncer_pool_waittime_service_file_template > $nrpe_check_pgbouncer_pool_waittime_service_file

# Create nagios user in pgbouncer
nagios_home=$(getent passwd nagios | awk -F: '{ print $6 }')
if [ ! -f ${nagios_home}/.pgpass ] || [ ! -f /var/lib/juju/nagios.password ]; then
    password=$(pwgen -s 16)
    nagios_home=$(getent passwd nagios | awk -F: '{ print $6 }')
    if [ -d $nagios_home ]; then
        echo "*:*:*:nagios:${password}" > ${nagios_home}/.pgpass
        chown nagios:nagios ${nagios_home}/.pgpass
        chmod 600 ${nagios_home}/.pgpass
    else
        juju-log "No home directory for nagios"
        exit 1
    fi
    if [ -d /var/lib/juju/ ]; then
        echo "${password}" > /var/lib/juju/nagios.password
        update_config
    else
        juju-log "No /var/lib/juju directory"
        exit 1
    fi
fi

# Reload NRPE
if [ -x /etc/init.d/nagios-nrpe-server ]; then
    service nagios-nrpe-server reload
else
    juju-log "Is NRPE installed?"
    exit 1
fi
