#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

unit_name=${JUJU_UNIT_NAME////-}
nagios_hostname="$(config-get nagios_context)-${unit_name}" 
nagios_logdir='/var/log/nagios'
nagios_check_script=/usr/local/lib/nagios/plugins/check-pgbouncer.py
nagios_servicegroup=$(config-get nagios_context)
address=$(config-get listen_addr)
if [ "$address" = "*" ]; then
	address=$(unit-get private-address)
fi

nagios_uid=$(getent passwd nagios | awk -F: '{ print $3}')
nagios_gid=$(getent passwd nagios | awk -F: '{ print $4}')
if [ $? -ne 0 ]; then
	juju-log "Nagios user not setup, exiting"
	exit 1
fi

if [ -d /usr/local/lib/nagios/plugins/ ]; then
	cp $CHARM_DIR/scripts/check-pgbouncer.py $nagios_check_script
	chmod 755 $nagios_check_script
fi

if [ ! -d $nagios_logdir ]; then
	mkdir $nagios_logdir
	chown nagios:nagios $nagios_logdir 
fi

# Remove existing checks to start clean
for FILE in /var/lib/nagios/export/*check_pgbouncer*.cfg; do
   rm -f $FILE
done

# Export Juju configs and relations.
juju_configs=$(/bin/mktemp --suffix=.juju)
config-get --format=json -o $juju_configs

# Insert variables
sed -i -e "s/}$/,\"nagios_hostname\": \"$nagios_hostname\" }/" $juju_configs
sed -i -e "s/}$/,\"address\": \"$address\" }/" $juju_configs
sed -i -e "s/}$/,\"nagios_servicegroup\": \"$nagios_servicegroup\" }/" $juju_configs

# NRPE check files
nrpe_check_pgbouncer_connection_count="/etc/nagios/nrpe.d/check_pgbouncer_connection_count.cfg"
nrpe_check_pgbouncer_pool_waittime="/etc/nagios/nrpe.d/check_pgbouncer_pool_waittime.cfg"
nrpe_check_pgbouncer_connection_count_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_connection_count.tmpl"
nrpe_check_pgbouncer_pool_waittime_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_pool_waittime.tmpl"
scripts/template-generate.py -j $juju_configs $nrpe_check_pgbouncer_connection_count_template > $nrpe_check_pgbouncer_connection_count
scripts/template-generate.py -j $juju_configs $nrpe_check_pgbouncer_pool_waittime_template > $nrpe_check_pgbouncer_pool_waittime

# Exported service files
nrpe_check_pgbouncer_connection_count_service_file="/var/lib/nagios/export/service__${nagios_servicegroup}-${nagios_hostname}_check_pgbouncer_connection_count.cfg"
nrpe_check_pgbouncer_pool_waittime_service_file="/var/lib/nagios/export/service__${nagios_servicegroup}-${nagios_hostname}_check_pgbouncer_pool_waittime.cfg"
nrpe_check_pgbouncer_connection_count_service_file_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_connection_count_service_file.tmpl"
nrpe_check_pgbouncer_pool_waittime_service_file_template="${CHARM_DIR}/templates/nrpe_check_pgbouncer_pool_waittime_service_file.tmpl"
scripts/template-generate.py -j $juju_configs $nrpe_check_pgbouncer_connection_count_service_file_template > $nrpe_check_pgbouncer_connection_count_service_file
scripts/template-generate.py -j $juju_configs $nrpe_check_pgbouncer_pool_waittime_service_file_template > $nrpe_check_pgbouncer_pool_waittime_service_file

# Clean up
rm -f $juju_configs

# Reload NRPE
if [ -x /etc/init.d/nagios-nrpe-server ]; then
	service nagios-nrpe-server reload
else
	juju-log "Is NRPE installed?"
	exit 1
fi
