#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm start hook

set -eux # -x for verbose logging to juju debug-log
. scripts/common

# Start pgbouncer if it is not running
# Reload if pgbouncer is already running
if /etc/init.d/pgbouncer status > /dev/null; then
        juju-log "Reloading pgbouncer"
        /usr/sbin/service pgbouncer reload
else
        juju-log "Starting pgbouncer"
        /usr/sbin/service pgbouncer start
fi

