#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm start hook

set -eux # -x for verbose logging to juju debug-log
. hooks/common

juju-log "Starting pgbouncer"
/usr/sbin/service pgbouncer start
