#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm stop hook

set -eux # -x for verbose logging to juju debug-log
. scripts/common

# Stop if pgbouncer is running
/usr/sbin/service pgbouncer status
if [ $? -eq 0 ]; then
	juju-log "Stopping pgbouncer"
	/usr/sbin/service pgbouncer stop
fi
