#!/bin/bash

# Copyright 2012 Canonical Ltd. All rights reserved.
# Author: Haw Loeung <haw.loeung@canonical.com>

# pgbouncer charm common functions used by various hooks

set -eux # -x for verbose logging to juju debug-log

SERVICE_AFFECTING_PACKAGES="pgbouncer"

update_config()
{
	pgbouncer_userlist=/etc/pgbouncer/userlist.txt
	local pgbouncer_userlist_new=$(/bin/mktemp --suffix=.juju)
	for file in $(find /var/lib/juju/ -maxdepth 1 -name '*\.password' -type f); do
		pgbouncer_user=$(basename $file | awk -F. '{print $1}')
		echo "\"$pgbouncer_user\" \"$(cat $file)\"" >> $pgbouncer_userlist_new
	done
	chown postgres:postgres $pgbouncer_userlist_new
	chmod 600 $pgbouncer_userlist_new
	mv $pgbouncer_userlist_new $pgbouncer_userlist

	local pgbouncer_config="/etc/pgbouncer/pgbouncer.ini"
	local general_template="templates/pgbouncer.ini.general.tmpl"

	# Export Juju configs and relations.
	local juju_configs=$(/bin/mktemp --suffix=.juju)
	config-get --format=json -o $juju_configs

	# Copy existing config file to preserve permissions.
        local pgbouncer_config_new=$(/bin/mktemp --suffix=.juju)
	cp -a $pgbouncer_config $pgbouncer_config_new

	# Generate the "databases" section first from list of Juju relations.
	echo "[databases]" > $pgbouncer_config_new 
	(find /var/lib/juju/ -maxdepth 1 -name 'db-*' -type f -print0 | xargs --null cat) \
		>> $pgbouncer_config_new

	# Generate the general "pgbouncer" section with configuration options
	# from Juju's configs.
	# Need to use cheetah cli. Setup vars and excuete cheetah-compile???
	scripts/template-generate.py -j $juju_configs $general_template \
		>> $pgbouncer_config_new

	# Looks good, let's make it live.
	mv $pgbouncer_config_new $pgbouncer_config

	# Clean up
	rm -f $pgbouncer_userlist_new $juju_configs $pgbouncer_config_new

	juju-log "reloading pgbouncer"
	service pgbouncer reload || exit 1
}

ensure_package_status()
{
	packages="$1" ; shift
	status="$1" ; shift

	case $status in
	install|hold)
		for package in ${packages}; do
			echo ${package} ${status}
		done | dpkg --set-selections
		;;
	*)
		;;
	esac
}
